Updated.

diff --git a/hacking-labs b/hacking-labs
--- a/hacking-labs
+++ b/hacking-labs
@@ -61,7 +61,7 @@ shopt -s nullglob
 
 # ************************* global variable definitions ************************
 g_PROGNAME="$(basename "${0}")"
-g_VERSION="0.0.1"
+g_VERSION="0.0.3"
 g_PROGRAM_NAME="hacking-labs"
 g_PROGRAM_DESCRIPTION="A script used to change the TCP/IP addresses of the isolated machines in the CIT-254 lab enviornment."
 g_SCRIPT_URL="https://github.com/DoctorKisow/CIT-254/raw/main/hacking-labs"
@@ -145,6 +145,7 @@ check_and_install_required()
         fi
     fi
 }
+
 # (cleanup_and_exit_with_code) - Function used to properly cleanup the enviornment after an error; the passed value are 1 (error) or 0 (normal).
 function cleanup_and_exit_with_code ()
 {
@@ -442,7 +443,6 @@ function warning ()
 # (increment_ip) - A function that will increment the network number passed ($1) by the second arguement ($2).
 function increment_ip ()
 {
-
   l_RNG='^[1-6]+$'
   if ! [[ $2 =~ $l_RNG ]]; then
     error "Function: increment_ip was passed a value that is out of bounds."
@@ -559,190 +559,190 @@ function settcpip ()
 
   info "SETTING: Setting the TCPIP addresses for the private network lab enviornment."
 
-  # ## PRE-ENVIORNMENT CHECK
-  #   #  Bring up and test DHCP IP for the public network.
-  #   info "  Checking connectivity on Kali Linux (Public Network)."
-  #   l_KALI_ETH0=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
-  #   if [[ -z "$l_KALI_ETH0" ]]; then
-  #     info "    KALI: Attempting to bring up the eth0 on Kali Linux."
+  ## PRE-ENVIORNMENT CHECK
+    #  Bring up and test DHCP IP for the public network.
+    info "  Checking connectivity on Kali Linux (Public Network)."
+    l_KALI_ETH0=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
+    if [[ -z "$l_KALI_ETH0" ]]; then
+      info "    KALI: Attempting to bring up the eth0 on Kali Linux."
 
-  #     nmcli conn up id "Public Network"
-  #     if [ "$?" -ne 0]; then
-  #       error "    KALI: Interface eth0 is not receiving a DHCP address from the host network."
-  #     fi
-  #   fi
+      nmcli conn up id "Public Network"
+      if [ "$?" -ne 0]; then
+        error "    KALI: Interface eth0 is not receiving a DHCP address from the host network."
+      fi
+    fi
 
-  #   # Bring ip and test default IP for attack network.
-  #   info "  Checking connectivity on Kali Linux (Attack_Network)."
-  #   l_KALI_ETH1=$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
-  #   if [[ -z "$l_KALI_ETH1" ]]; then
-  #     info "    KALI: Attempting to bring up the eth1 on Kali Linux."
+    # Bring ip and test default IP for attack network.
+    info "  Checking connectivity on Kali Linux (Attack_Network)."
+    l_KALI_ETH1=$(ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
+    if [[ -z "$l_KALI_ETH1" ]]; then
+      info "    KALI: Attempting to bring up the eth1 on Kali Linux."
 
-  #     nmcli conn up id "Attack_Network"
-  #     if [ "$?" -ne 0]; then
-  #       error "    KALI: Interface eth1 is not properly connected to the attack network."
-  #     fi
-  #   fi
+      nmcli conn up id "Attack_Network"
+      if [ "$?" -ne 0]; then
+        error "    KALI: Interface eth1 is not properly connected to the attack network."
+      fi
+    fi
 
-  #   info "  Ensuring each lab host is up and running."
-  #   if [[ "$l_KALI_ETH1" == "$g_KALI_DEFIP" ]]; then
-  #     # Check WIN2K8 is available.
-  #     l_WIN2K8_RESP=$(ping_and_report $g_WIN2K8_DEFIP)
-  #     if [[ $l_WIN2K8_RESP -ne 0 ]]; then
-  #       warning "    The Metasploitable3 (Microsoft Windows) VM is not responding."
-  #     else
-  #       info "   The Metasploitable3 (Microsoft Windows) VM is responding."
-  #     fi
+    info "  Ensuring each lab host is up and running."
+    if [[ "$l_KALI_ETH1" == "$g_KALI_DEFIP" ]]; then
+      # Check WIN2K8 is available.
+      l_WIN2K8_RESP=$(ping_and_report $g_WIN2K8_DEFIP)
+      if [[ $l_WIN2K8_RESP -ne 0 ]]; then
+        warning "    The Metasploitable3 (Microsoft Windows) VM is not responding."
+      else
+        info "   The Metasploitable3 (Microsoft Windows) VM is responding."
+      fi
 
-  #     # Check Metasploitable3 (Linux) is available.
-  #     l_LIN1404_RESP=$(ping_and_report $g_LIN1404_DEFIP)
-  #     if [[ $l_LIN1404_RESP -ne 0 ]]; then
-  #       warning "    The Metasploitable3 (Linux) VM is not responding."
-  #     else
-  #       info "    The Metasploitable3 (Linux) VM is responding."
-  #     fi
+      # Check Metasploitable3 (Linux) is available.
+      l_LIN1404_RESP=$(ping_and_report $g_LIN1404_DEFIP)
+      if [[ $l_LIN1404_RESP -ne 0 ]]; then
+        warning "    The Metasploitable3 (Linux) VM is not responding."
+      else
+        info "    The Metasploitable3 (Linux) VM is responding."
+      fi
 
-  #     # Check Metaspliotable2 (Linux) is available.
-  #     l_LIN0804_RESP=$(ping_and_report $g_LIN0804_DEFIP)
-  #     if [[ $l_LIN0804_RESP -ne 0 ]]; then
-  #       warning "    The Metasploitable2 (Linux) VM is not responding."
-  #     else
-  #       info "    The Metasploitable2 (Linux) VM is responding."
-  #     fi
+      # Check Metaspliotable2 (Linux) is available.
+      l_LIN0804_RESP=$(ping_and_report $g_LIN0804_DEFIP)
+      if [[ $l_LIN0804_RESP -ne 0 ]]; then
+        warning "    The Metasploitable2 (Linux) VM is not responding."
+      else
+        info "    The Metasploitable2 (Linux) VM is responding."
+      fi
 
-  #     # Any host that is unavailable will cause script to fail, exit with error.
-  #     if [[ $l_WIN2K8_RESP -ne 0 ]] || [[ $l_LIN1404_RESP -ne 0 ]] || [[ $l_LIN0804_RESP -ne 0 ]]; then
-  #       error "    One or more of the josts in the lab enviornment are unresponsive. Please ensure each host is up prior to running this script."
-  #     else
-  #       info "    The lab host enviornment is up and ready to configure."
-  #     fi
-  #   fi
-  # ## PRE-ENVIORNMENT CHECK
+      # Any host that is unavailable will cause script to fail, exit with error.
+      if [[ $l_WIN2K8_RESP -ne 0 ]] || [[ $l_LIN1404_RESP -ne 0 ]] || [[ $l_LIN0804_RESP -ne 0 ]]; then
+        error "    One or more of the josts in the lab enviornment are unresponsive. Please ensure each host is up prior to running this script."
+      else
+        info "    The lab host enviornment is up and ready to configure."
+      fi
+    fi
+  ## PRE-ENVIORNMENT CHECK
 
-  # ## Metasploitable3 (Microsoft Windows)
-  #   info "  Updating the Metasploitable3 (Microsoft Windows) VM networking."
-  #   sleep 5s
+  ## Metasploitable3 (Microsoft Windows)
+    info "  Updating the Metasploitable3 (Microsoft Windows) VM networking."
+    sleep 5s
 
-  #   info "    Running TCPIP update script on Metasploitable3 (Microsoft Windows)."
-  #   sshpass -pvagrant ssh -f -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" vagrant@$g_WIN2K8_DEFIP 'netsh interface ip set address name="Attack_Network" static '"$l_WIN2K8_NEWIP"' 255.255.255.248'
-  # ## Metasploitable3 (Microsoft Windows)
+    info "    Running TCPIP update script on Metasploitable3 (Microsoft Windows)."
+    sshpass -pvagrant ssh -f -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" vagrant@$g_WIN2K8_DEFIP 'netsh interface ip set address name="Attack_Network" static '"$l_WIN2K8_NEWIP"' 255.255.255.248'
+  ## Metasploitable3 (Microsoft Windows)
 
-  # ## Metasploitable3 (Linux)
-  #   info "  Updating the Metasploitable3 (Linux) VM networking."
-  #   sleep 5s
+  ## Metasploitable3 (Linux)
+    info "  Updating the Metasploitable3 (Linux) VM networking."
+    sleep 5s
 
-  #   # Cleanup incase of a borked run.
-  #   if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin1404.sh" ]]; then
-  #     info "    Cleaning up messy environment, removing bootstrap_lin1404.sh script."
-  #     rm "${g_SCRIPT_PATH}/bootstrap_lin1404.sh"
-  #   fi
+    # Cleanup incase of a borked run.
+    if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin1404.sh" ]]; then
+      info "    Cleaning up messy environment, removing bootstrap_lin1404.sh script."
+      rm "${g_SCRIPT_PATH}/bootstrap_lin1404.sh"
+    fi
 
-  #   # Cleanup incase of a borked run.
-  #   if [[ -f "${g_SCRIPT_PATH}/updater_lin1404.sh" ]]; then
-  #     info "    Cleaning up messy environment, removing updater_lin1404.sh script."
-  #     rm "${g_SCRIPT_PATH}/updater_lin1404.sh"
-  #   fi
+    # Cleanup incase of a borked run.
+    if [[ -f "${g_SCRIPT_PATH}/updater_lin1404.sh" ]]; then
+      info "    Cleaning up messy environment, removing updater_lin1404.sh script."
+      rm "${g_SCRIPT_PATH}/updater_lin1404.sh"
+    fi
 
-  #   # Create bootstrap script that will call the updater script.
-  #   info "    Creating bootstrap script."
-  #   printf '#!/bin/bash\n\n' >> bootstrap_lin1404.sh
-  #   printf "echo vagrant | sudo -S nohup /home/vagrant/updater.sh &\n" >> bootstrap_lin1404.sh
-  #   printf "rm /home/vagrant/bootstrap.sh\n" >> bootstrap_lin1404.sh
-  #   chmod +x bootstrap_lin1404.sh
+    # Create bootstrap script that will call the updater script.
+    info "    Creating bootstrap script."
+    printf '#!/bin/bash\n\n' >> bootstrap_lin1404.sh
+    printf "echo vagrant | sudo -S nohup /home/vagrant/updater.sh &\n" >> bootstrap_lin1404.sh
+    printf "rm /home/vagrant/bootstrap.sh\n" >> bootstrap_lin1404.sh
+    chmod +x bootstrap_lin1404.sh
 
-  #   # Create the updater script based on default ip address and new onr entered.
-  #   info "    Creating TCPIP address updater script."
-  #   printf '#!/bin/bash\n\n' >> updater_lin1404.sh
-  #   printf "sleep 10s\n\n" >> updater_lin1404.sh
-  #   printf "sed -i -e 's/$g_LIN1404_DEFIP/$l_LIN1404_NEWIP/' /etc/network/interfaces\n" >> updater_lin1404.sh
-  #   printf "ifdown eth0 && ifup eth0\n" >> updater_lin1404.sh
-  #   printf "rm /home/vagrant/updater.sh\n" >> updater_lin1404.sh
-  #   chmod +x updater_lin1404.sh
+    # Create the updater script based on default ip address and new onr entered.
+    info "    Creating TCPIP address updater script."
+    printf '#!/bin/bash\n\n' >> updater_lin1404.sh
+    printf "sleep 10s\n\n" >> updater_lin1404.sh
+    printf "sed -i -e 's/$g_LIN1404_DEFIP/$l_LIN1404_NEWIP/' /etc/network/interfaces\n" >> updater_lin1404.sh
+    printf "ifdown eth0 && ifup eth0\n" >> updater_lin1404.sh
+    printf "rm /home/vagrant/updater.sh\n" >> updater_lin1404.sh
+    chmod +x updater_lin1404.sh
 
-  #   # Copy scripts to the Metasploitable3 (Linux) VM.
-  #   sshpass -pvagrant scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" updater_lin1404.sh vagrant@$g_LIN1404_DEFIP:/home/vagrant/updater.sh
-  #   sshpass -pvagrant scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" bootstrap_lin1404.sh vagrant@$g_LIN1404_DEFIP:/home/vagrant/bootstrap.sh
+    # Copy scripts to the Metasploitable3 (Linux) VM.
+    sshpass -pvagrant scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" updater_lin1404.sh vagrant@$g_LIN1404_DEFIP:/home/vagrant/updater.sh
+    sshpass -pvagrant scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" bootstrap_lin1404.sh vagrant@$g_LIN1404_DEFIP:/home/vagrant/bootstrap.sh
 
-  #   # Run the SSH script
-  #   info "    Running TCPIP update script on Metasploitable3 (Linux)."
-  #   sshpass -pvagrant ssh -f -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" vagrant@$g_LIN1404_DEFIP '/bin/bash /home/vagrant/bootstrap.sh'
-  #   if [ $? -eq 0 ]; then
-  #     info "    TCPIP address updater script ran successfully."
-  #   fi
+    # Run the SSH script
+    info "    Running TCPIP update script on Metasploitable3 (Linux)."
+    sshpass -pvagrant ssh -f -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" vagrant@$g_LIN1404_DEFIP '/bin/bash /home/vagrant/bootstrap.sh'
+    if [ $? -eq 0 ]; then
+      info "    TCPIP address updater script ran successfully."
+    fi
 
-  #   # Cleanup after run.
-  #   if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin1404.sh" ]]; then
-  #     info "    Cleaning up removing bootstrap_lin1404.sh script."
-  #     rm "${g_SCRIPT_PATH}/bootstrap_lin1404.sh"
-  #   fi
+    # Cleanup after run.
+    if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin1404.sh" ]]; then
+      info "    Cleaning up removing bootstrap_lin1404.sh script."
+      rm "${g_SCRIPT_PATH}/bootstrap_lin1404.sh"
+    fi
 
-  #   if [[ -f "${g_SCRIPT_PATH}/updater_lin1404.sh" ]]; then
-  #     info "    Cleaning up removing updater_lin1404.sh script."
-  #     rm "${g_SCRIPT_PATH}/updater_lin1404.sh"
-  #   fi
-  # ## Metasploitable3 (Linux)
+    if [[ -f "${g_SCRIPT_PATH}/updater_lin1404.sh" ]]; then
+      info "    Cleaning up removing updater_lin1404.sh script."
+      rm "${g_SCRIPT_PATH}/updater_lin1404.sh"
+    fi
+  ## Metasploitable3 (Linux)
 
-  # ## Metasploitable2 (Linux)
-  #   info "  Updating the Metasploitable2 VM networking."
-  #   sleep 5s
+  ## Metasploitable2 (Linux)
+    info "  Updating the Metasploitable2 VM networking."
+    sleep 5s
 
-  #   # Cleanup incase of a borked run.
-  #   if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin0804.sh" ]]; then
-  #     info "    Cleaning up messy environment, removing bootstrap_lin0804.sh script."
-  #     rm "${g_SCRIPT_PATH}/bootstrap_lin0804.sh"
-  #   fi
+    # Cleanup incase of a borked run.
+    if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin0804.sh" ]]; then
+      info "    Cleaning up messy environment, removing bootstrap_lin0804.sh script."
+      rm "${g_SCRIPT_PATH}/bootstrap_lin0804.sh"
+    fi
 
-  #   # Cleanup incase of a borked run.
-  #   if [[ -f "${g_SCRIPT_PATH}/updater_lin0804.sh" ]]; then
-  #     info "    Cleaning up messy environment, removing updater_lin0804.sh script."
-  #     rm "${g_SCRIPT_PATH}/updater_lin0804.sh"
-  #   fi
+    # Cleanup incase of a borked run.
+    if [[ -f "${g_SCRIPT_PATH}/updater_lin0804.sh" ]]; then
+      info "    Cleaning up messy environment, removing updater_lin0804.sh script."
+      rm "${g_SCRIPT_PATH}/updater_lin0804.sh"
+    fi
 
-  #   # Create bootstrap script that will call the updater script.
-  #   info "    Creating bootstrap script."
-  #   printf '#!/bin/bash\n\n' >> bootstrap_lin0804.sh
-  #   printf "echo msfadmin | sudo -S nohup /home/msfadmin/updater.sh &\n" >> bootstrap_lin0804.sh
-  #   printf "rm /home/msfadmin/bootstrap.sh\n" >> bootstrap_lin0804.sh
-  #   chmod +x bootstrap_lin0804.sh
+    # Create bootstrap script that will call the updater script.
+    info "    Creating bootstrap script."
+    printf '#!/bin/bash\n\n' >> bootstrap_lin0804.sh
+    printf "echo msfadmin | sudo -S nohup /home/msfadmin/updater.sh &\n" >> bootstrap_lin0804.sh
+    printf "rm /home/msfadmin/bootstrap.sh\n" >> bootstrap_lin0804.sh
+    chmod +x bootstrap_lin0804.sh
 
-  #   # Create the updater script based on default ip address and new onr entered.
-  #   info "    Creating TCPIP address updater script."
-  #   printf '#!/bin/bash\n\n' >> updater_lin0804.sh
-  #   printf "sleep 10s\n\n" >> updater_lin0804.sh
-  #   printf "sed -i -e 's/$g_LIN0804_DEFIP/$l_LIN0804_NEWIP/' /etc/network/interfaces\n" >> updater_lin0804.sh
-  #   printf "ifdown eth0 && ifup eth0\n" >> updater_lin0804.sh
-  #   printf "rm /home/msfadmin/updater.sh\n" >> updater_lin0804.sh
-  #   chmod +x updater_lin0804.sh
+    # Create the updater script based on default ip address and new onr entered.
+    info "    Creating TCPIP address updater script."
+    printf '#!/bin/bash\n\n' >> updater_lin0804.sh
+    printf "sleep 10s\n\n" >> updater_lin0804.sh
+    printf "sed -i -e 's/$g_LIN0804_DEFIP/$l_LIN0804_NEWIP/' /etc/network/interfaces\n" >> updater_lin0804.sh
+    printf "ifdown eth0 && ifup eth0\n" >> updater_lin0804.sh
+    printf "rm /home/msfadmin/updater.sh\n" >> updater_lin0804.sh
+    chmod +x updater_lin0804.sh
 
-  #   # Copy scripts to the Metasploitable2 VM.
-  #   sshpass -pmsfadmin scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" updater_lin0804.sh msfadmin@$g_LIN0804_DEFIP:/home/msfadmin/updater.sh
-  #   sshpass -pmsfadmin scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" bootstrap_lin0804.sh msfadmin@$g_LIN0804_DEFIP:/home/msfadmin/bootstrap.sh
+    # Copy scripts to the Metasploitable2 VM.
+    sshpass -pmsfadmin scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" updater_lin0804.sh msfadmin@$g_LIN0804_DEFIP:/home/msfadmin/updater.sh
+    sshpass -pmsfadmin scp -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" bootstrap_lin0804.sh msfadmin@$g_LIN0804_DEFIP:/home/msfadmin/bootstrap.sh
 
-  #   # Run the SSH script
-  #   info "    Running TCPIP update script on Metasploitable2."
-  #   sshpass -pmsfadmin ssh -f -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" msfadmin@$g_LIN0804_DEFIP '/bin/bash /home/msfadmin/bootstrap.sh'
-  #   if [ $? -eq 0 ]; then
-  #     info "    TCPIP address updater script ran successfully."
-  #   fi
+    # Run the SSH script
+    info "    Running TCPIP update script on Metasploitable2."
+    sshpass -pmsfadmin ssh -f -o "StrictHostKeyChecking no" -o "HostKeyAlgorithms=+ssh-dss" msfadmin@$g_LIN0804_DEFIP '/bin/bash /home/msfadmin/bootstrap.sh'
+    if [ $? -eq 0 ]; then
+      info "    TCPIP address updater script ran successfully."
+    fi
 
-  #   # Cleanup after run.
-  #   if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin0804.sh" ]]; then
-  #     info "    Cleaning up removing bootstrap_lin0804.sh script."
-  #     rm "${g_SCRIPT_PATH}/bootstrap_lin0804.sh"
-  #   fi
+    # Cleanup after run.
+    if [[ -f "${g_SCRIPT_PATH}/bootstrap_lin0804.sh" ]]; then
+      info "    Cleaning up removing bootstrap_lin0804.sh script."
+      rm "${g_SCRIPT_PATH}/bootstrap_lin0804.sh"
+    fi
 
-  #   if [[ -f "${g_SCRIPT_PATH}/updater_lin0804.sh" ]]; then
-  #     info "    Cleaning up removing updater_lin0804.sh script."
-  #     rm "${g_SCRIPT_PATH}/updater_lin0804.sh"
-  #   fi
-  # ## Metasploitable2 (Linux)
+    if [[ -f "${g_SCRIPT_PATH}/updater_lin0804.sh" ]]; then
+      info "    Cleaning up removing updater_lin0804.sh script."
+      rm "${g_SCRIPT_PATH}/updater_lin0804.sh"
+    fi
+  ## Metasploitable2 (Linux)
 
-  # ## KALI
-  #  info "  Updating Kali Linux (eth1) VM networking."
-  #  nmcli connection down Attack_Network > /dev/nul
-  #  nmcli connection modify Attack_Network ipv4.addresses $l_KALI_NEWIP/29
-  #  nmcli connection up Attack_Network > /dev/nul
-  # ## KALI
+  ## KALI
+   info "  Updating Kali Linux (eth1) VM networking."
+   nmcli connection down Attack_Network > /dev/nul
+   nmcli connection modify Attack_Network ipv4.addresses $l_KALI_NEWIP/29
+   nmcli connection up Attack_Network > /dev/nul
+  ## KALI
 
   ## POST-ENVIORNMENT CHECK
     # Check KALI is available.
@@ -784,6 +784,15 @@ function settcpip ()
       info "    The lab host enviornment has successfully been reconfigured."
     fi
   ## POST-ENVIORNMENT CHECK
+
+  ## WRITE LAB FILE
+    printf "This is Kali Linux (2023.4)\n\nThis virtual machine (VM) is part of a lab environment that includes three isolated virtual machines that are vulnerable and designed to teach you the tools used to attack and defend networks. Using this VM, you can conduct security training, test security tools, and practice standard penetration testing techniques.\n\n" >> /home/labuser/Desktop/Lab-Readme.txt
+    printf "This lab enviornment is setup with the following IP addresses:\n" >> /home/labuser/Desktop/Lab-Readme.txt
+    printf "Kali Linux v2023.4 (This VM)\n  eth0: DHCP\n  eth1: $l_KALI_NEWIP/29\n\n" >> /home/labuser/Desktop/Lab-Readme.txt
+    printf "Metasploitable 3 (W2K8R2)\n  nic0: $l_WIN2K8_NEWIP/29\n\n" >> /home/labuser/Desktop/Lab-Readme.txt
+    printf "Metasploitable 3 (Linux)\n  eth0: $l_LIN1404_NEWIP/29\n\n"  >> /home/labuser/Desktop/Lab-Readme.txt
+    printf "Metasploitable 2 (Linux)\n  eth0: $l_LIN0804_NEWIP/29\n\n" >> /home/labuser/Desktop/Lab-Readme.txt
+  ## WRITE LAB FILE
 }
 # ************************* end script specific functions **********************
 
