v0.0.21

diff --git a/hacking-labs b/hacking-labs
--- a/hacking-labs
+++ b/hacking-labs
@@ -66,7 +66,7 @@ shopt -s nullglob
 
 # ************************* global variable definitions ************************
 g_PROGNAME="$(basename "${0}")"
-g_VERSION="0.0.20"
+g_VERSION="0.0.21"
 g_PROGRAM_NAME="hacking-labs"
 g_PROGRAM_DESCRIPTION="A script used to change the TCP/IP addresses of the isolated machines in the CIT-254 lab enviornment."
 g_SCRIPT_URL="https://github.com/DoctorKisow/CIT-254/raw/main/hacking-labs"
@@ -378,13 +378,13 @@ function update ()
   local l_ABS_PATH
   local l_VERSION
 
-  info "Checking for updates to the $g_PROGRAM_NAME script."
+  info " UPDATE: Checking for updates to the $g_PROGRAM_NAME script."
 
   cd "${g_SCRIPT_PATH}"
 
   # Test internet access.
   ping -q -c1 8.8.8.8 &>/dev/null
-  if [ $? -eq 1 ]; then
+  if [ $? == 1 ]; then
     warning "This script does not have a required network connection to update itself."
     return
   fi
@@ -559,6 +559,10 @@ function settcpip ()
   ## PRE-ENVIRONMENT CHECK
     # Cleanup cloned environment.
     info "  Cleaning up from the cloned environment..."
+
+    # Disable exiting immediately if a command exits with a non-zero status.
+    set +e
+
     nmcli connection | grep -q 'Wired connection 1'
     if [ $? == 0 ]; then
       info "    Removing cloned eth0 network adapter..."
@@ -590,6 +594,9 @@ function settcpip ()
       nmcli con add con-name "CIT-254-ISOLATED" type ethernet ifname eth1 ipv4.method manual ipv4.address 192.168.1.1/29
       nmcli connection up id "CIT-254-ISOLATED"
     fi
+
+    # Enable exiting immediately if a command exits with a non-zero status.
+    set -e
 
     info "  Ensuring each lab host is up and running."
     if [[ "$l_KALI_ETH1" == "$g_KALI_DEFIP" ]]; then
